name: team-label
on: [pull_request]
jobs:
  build:
    defaults:
      run:
        runs-on: ubuntu-latest
    steps:
    - name: Checkout to team repo
      uses: actions/checkout@main
      with:
        repository: guillenvd/eng-team-self
        token: ${{ secrets.PAT }}
        path: ./eng-team-self
    - name: Show Working directory
      run: |
        ls
        echo "position $(pwd)"
        echo " default ${{ env.working-directory }}"
        echo "üçè This job's status is ${{ job.status }}."
        runs-on: ubuntu-latest
    - uses: JulienKode/team-labeler-action@v0.1.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"